#!/bin/bash


get_os() {

    local os=""
    local kernelName=""

    kernelName="$(uname -s)"

    # figure out what kernel matches to set os name (macOS and Ubuntu only)
    if [ "$kernelName" == "Darwin" ]; then
        os="macos"
    elif [ "$kernelName" == "Linux" ] && [ -e "/etc/lsb-release" ]; then
        os="ubuntu"
    else
        os="$kernelName"
    fi

    printf "%s" "$os"
}


source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_aliases"
        "bash_exports"
        "bash_options"
        "bash_prompt"
        "hushlogin"
        "curlrc"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    cd "$CURRENT_DIRECTORY"
}

source_bash_files
unset -f source_bash_files

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).
clear
