#!/bin/bash

# actually clear the screen
alias clear=clear && printf '\e[3J'

# Show/hide hidden files in Finder
alias show-files="defaults write com.apple.finder AppleShowAllFiles -bool true \
                    && killall Finder"
alias hide-files="defaults write com.apple.finder AppleShowAllFiles -bool false \
                    && killall Finder"


# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
# Finally, clear download history from quarantine. https://mths.be/bum
alias empty-trash="sudo rm -frv /Volumes/*/.Trashes; \
                   sudo rm -frv ~/.Trash; \
                   sudo rm -frv /private/var/log/asl/*.asl; \
                   sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"


# Recursively delete `.DS_Store` files
alias clean-up="find . -type f -name '*.DS_Store' -ls -delete"


# Clear DNS cache.
alias clear-dns-cache="sudo dscacheutil -flushcache; \
                       sudo killall -HUP mDNSResponder"


# Get IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' \
                | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

