#!/bin/bash


# Shorter commands for the `Advanced Packaging Tool`
alias apti="sudo apt-get install"
alias aptr="sudo apt-get remove"
alias apts="sudo apt-cache search"
alias aptu="sudo apt-get update \
                && sudo apt-get upgrade"


# Empty trash.
alias empty-trash="rm -rf ~/.local/share/Trash/files/*"


# Hide/Show desktop icons.
alias show-files="gsettings set org.gnome.desktop.background show-desktop-icons true"
alias hide-files="gsettings set org.gnome.desktop.background show-desktop-icons false"


# Get local IP.
alias localip="ifconfig \
                | grep 'inet addr' \
                | grep -v '127.0.0.1' \
                | cut -d: -f2 \
                | cut -d' ' -f1"


# Open from the terminal.
alias open="xdg-open"
